CREATE TABLE PACIENTE
(
	ID_PACIENTE NUMBER NOT NULL,
	CPF NUMBER NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASC DATE,
	DATA_REGISTRO DATE,
	SEXO VARCHAR(1) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(15),
	MEDICO VARCHAR(100) NOT NULL,
	OCUPACAO VARCHAR(50),
	QUADRO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_PACIENTE PRIMARY KEY(CPF),
	CONSTRAINT CK_PACIENTE CHECK(DATA_NASC < DATA_REGISTRO)
);